["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
player = ["src/player.cairo"]
tournament = ["src/tournament.cairo"]

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/cairo_math_64x61/contracts"]

["protostar.test"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/cairo_math_64x61/contracts"]
