[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

[contracts]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/proxy.cairo"]
player = ["src/player.cairo"]
tournament = ["src/tournament.cairo"]
